---
  env:
    browser: true
    node: true
    es6: true
    mocha: true

  parser: babel-eslint
  parserOptions:
    ecmaVersion: 7
    ecmaFeatures:
      jsx: true

  extends:
    - "eslint:recommended"
    - "plugin:react/recommended"

  plugins:
    - react

  rules:
    "array-bracket-spacing":
      - warn
      - never
    "block-spacing": warn
    "brace-style":
      - error
      - stroustrup
    "eol-last": error
    indent:
      - warn
      - 2
      - SwitchCase: 1
    "jsx-quotes": warn
    "key-spacing": warn
    "keyword-spacing": warn
    "newline-after-var": warn
    "newline-before-return": warn
    "no-lonely-if": error
    "no-multi-spaces": warn
    "no-whitespace-before-property": error
    "padded-blocks":
      - error
      - never
    "prefer-rest-params": warn
    quotes:
      - warn
      - single
    "react/jsx-boolean-value": warn
    "react/jsx-closing-bracket-location":
      - warn
      - line-aligned
    "react/no-multi-comp": warn
    "react/no-unknown-property": warn
    "react/prop-types": warn
    "react/self-closing-comp": warn
    "react/wrap-multilines": warn
    "space-before-blocks": warn
    "space-before-function-paren":
      - warn
      - never
    "space-infix-ops":
      - error
      - int32Hint: false
    "space-unary-ops": warn
